project:
  type: website
  output-dir: _site
website:
  title: Nathans Stats Stuff
  site-url: https://NathOrmond.github.io/stats-concepts
  navbar:
    left:
    - href: index.qmd
      text: Home
    - text: Teaching Stats
      menu:
      - href: src/teaching-stats/core-concepts/index.qmd
        text: Core Concepts
    - text: Blog
      menu:
      - href: src/blog/paper-reviews/index.qmd
        text: Paper Reviews
    - href: about.qmd
      text: About
execute:
  freeze: auto
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: Show the code
    bibliography: references.bib
editor: visual
