project:
  type: website
  output-dir: _site

website:
  title: "Statistics Notes"
  site-url: "https://NathOrmond.github.io/stats-concepts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Concepts"
        menu:
          - href: concepts/central-limit-theorem.qmd
            text: "Central Limit Theorem"
          - href: concepts/degrees-of-freedom.qmd
            text: "Degrees of Freedom"
      - text: "Analysis and Discussion of Papers"
        menu:
          - href: misc/papers/index.qmd
            text: "Overview"
          - href: misc/papers/chatbot-mental-health/chatbot-postpartum-mental-health.qmd
            text: "Chatbot Effects on Postpartum Mental Health"
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
    bibliography: references.bib

editor: visual

