name: stats-notes-python 
dependencies:
  - python=3.12
  - pip
  - jupyterlab
  - pip:
      - google-api-python-client
      - python-dotenv
      - pandas
      - matplotlib
      - seaborn
      - nltk
      - wordcloud
      - scikit-learn
